#!/usr/bin/env bash

if [ -d "/Applications" ]; then PLATFORM='ios'; else PLATFORM='android'; fi

cp -a config-"${PLATFORM}".xml config.xml

#cordova build "${PLATFORM}" --device
cordova build "${PLATFORM}"
