#!/usr/bin/env bash
if [ $1 == ios ]; then PLATFORM='ios'; else PLATFORM='android'; fi
#if [ -d "/Applications" ]; then PLATFORM='ios'; else PLATFORM='android'; fi

cp -a config-"${PLATFORM}".xml config.xml

cordova build "${PLATFORM}"
